version: '3'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbpassword
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=dw2911_db
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    depends_on:
      - db
    environment:
      - PMA_HOST=db
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 8080:80
  
  api:
    build: ./backend
    container_name: running-backend
    restart: always
    depends_on:
      - db
    expose:
      - 9000
  
  ui:
    build: ./frontend
    container_name: running-frontend
    restart: always
    expose:
      - 80

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "8000:8000"
      - "8001:80"
