"""Mensagem com remetente de api_v2

Revision ID: 28e4572d2ec9
Revises: 
Create Date: 2021-10-30 00:24:06.852519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28e4572d2ec9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mensagem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('remetente', sa.String(length=20), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.Column('texto', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mensagem'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mensagem')
    # ### end Alembic commands ###
